import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import ReactMarkdown from 'react-markdown';

import axios from 'axios';

export const getStaticProps = async () => {
  const res = await axios.get('http://localhost:1337/posts/1');
  const postInfo = res.data;

  return {
    props: {
      postInfo
    }
  }
}

export default function Home({ postInfo }) {

  console.log(postInfo);
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          {postInfo.Title}
        </h1>
        <div>
          <ReactMarkdown>
            {postInfo.body}
          </ReactMarkdown>
        </div>
      </main>


    </div>
  )
}
